const prompts = {
  "creative-short-story": [
    "A haiku",
    "Eye contact",
    "Hope",
    "Windows",
    "Electricity",
    "Fear",
    "Jealousy",
    "Dreams",
    "Animals",
    "Cleaning",
    "Moon",
    "Revenge",
    "Sweet",
    "Desert",
    "Competition",
    "Wedding",
    "Plants",
    "Animals",
    "1000 years",
    "The future",
    "The past",
    "The present",
    "Sharing",
    "Umami",
    "Responsibility",
    "5 things you can see",
    "Art",
    "Places",
    "Alarm",
    "Books",
    "Spice",
    "Music",
    "Nostalgia",
    "Legends",
    "Brave",
    "Travel",
    "Smoke",
    "Doors",
    "Culture",
    "Light",
    "Community",
    "Puzzles",
    "Unknown",
    "Nature",
    "Secret",
    "Movies",
    "Joke",
    "Sport",
    "Tradition",
    "Coping",
    "Embarrassment",
    "Longing",
    "Heroic",
    "Advertisment",
    "Magic",
    "Wonder",
    "Adjective",
    "Whisper",
    "Heat",
    "4 things you feel",
    "Neighbours",
    "Flying",
    "Colour",
    "Forest",
    "Shape",
    "Contradiction",
    "Friendship",
    "Prizes",
    "Sour",
    "Winning",
    "Beach",
    "3 things you hear",
    "Proximity",
    "Direction",
    "Grow",
    "Scent",
    "Gift",
    "Ships",
    "Farming",
    "Stealing",
    "Isolation",
    "Dancing",
    "Energise",
    "Discover",
    "Manners",
    "2 things you smell",
    "Copy",
    "Empathy",
    "Strength",
    "Waterfall",
    "Breathe",
    "Time",
    "Influence",
    "Pattern",
    "Choice",
    "Concrete",
    "Experiment",
    "Cooking",
    "Forgive",
    "Teams",
    "Power",
    "Lyrics",
    "Obstacle",
    "Shrink",
    "Follow",
    "1 thing you taste",
    "Truth",
    "Resolution",
    "Movement",
    "Space",
    "Fortune",
    "Trust",
    "Starting",
    "Rain",
    "Inspiration",
    "Salty",
    "What was it like being 5 years old? Where were you? What did you look like?",
    "Size",
    "Transformation",
    "Balance",
    "Threat",
    "Substitute",
    "Adapt",
    "Smile",
    "Senses",
    "House boat",
    "Dry",
    "Cold",
    "Chances",
    "Questions",
    "A speech",
    "Promise",
    "Mix",
    "What if",
    "Thrill",
    "Science",
    "Detail",
    "Speed",
    "Sky",
    "Hobbies",
    "Bubbles",
    "What was it like being 10 years old? Where were you? What did you like?",
    "Graphic",
    "Explain",
    "Borrow",
    "Transport",
    "Contrast",
    "Memory",
    "Failure",
    "Swimming",
    "Bitter",
    "Names",
    "An obituary",
    "Switch",
    "Personal",
    "Mystery",
    "Minerals",
    "Communication",
    "Bragging",
    "Horror",
    "What was it like being 12 years old? What did you like? What did you dislike?",
    "Compare",
    "Mischief",
    "Paths",
    "Create",
    "Code",
    "Scavenge",
    "Self-portrait",
    "Challenge",
    "A newsletter",
    "Canvas",
    "Hybrid",
    "Maps",
    "Abstract",
    "A snail mail letter",
    "Mode",
    "Busy",
    "Passage",
    "Repetition",
    "A post card",
    "Resilience",
    "Play",
    "What is it like being you?",
    "Combine",
    "Ideas",
    "Favourites",
    "Themes",
    "Dwelling", // End of original entries
    "A haiku",
    "Eye contact",
    "Hope",
    "Windows",
    "Electricity",
    "Fear",
    "Jealousy",
    "Dreams",
    "Animals",
    "Cleaning",
    "Moon",
    "Revenge",
    "Sweet",
    "Desert",
    "Competition",
    "Wedding",
    "Plants",
    "Animals",
    "1000 years",
    "The future",
    "The past",
    "The present",
    "Sharing",
    "Umami",
    "Responsibility",
    "5 things you can see",
    "Art",
    "Places",
    "Alarm",
    "Books",
    "Spice",
    "Music",
    "Nostalgia",
    "Legends",
    "Brave",
    "Travel",
    "Smoke",
    "Doors",
    "Culture",
    "Light",
    "Community",
    "Puzzles",
    "Unknown",
    "Nature",
    "Secret",
    "Movies",
    "Joke",
    "Sport",
    "Tradition",
    "Coping",
    "Embarrassment",
    "Longing",
    "Heroic",
    "Advertisment",
    "Magic",
    "Wonder",
    "Adjective",
    "Whisper",
    "Heat",
    "4 things you feel",
    "Neighbours",
    "Flying",
    "Colour",
    "Forest",
    "Shape",
    "Contradiction",
    "Friendship",
    "Prizes",
    "Sour",
    "Winning",
    "Beach",
    "3 things you hear",
    "Proximity",
    "Direction",
    "Grow",
    "Scent",
    "Gift",
    "Ships",
    "Farming",
    "Stealing",
    "Isolation",
    "Dancing",
    "Energise",
    "Discover",
    "Manners",
    "2 things you smell",
    "Copy",
    "Empathy",
    "Strength",
    "Waterfall",
    "Breathe",
    "Time",
    "Influence",
    "Pattern",
    "Choice",
    "Concrete",
    "Experiment",
    "Cooking",
    "Forgive",
    "Teams",
    "Power",
    "Lyrics",
    "Obstacle",
    "Shrink",
    "Follow",
    "1 thing you taste",
    "Truth",
    "Resolution",
    "Movement",
    "Space",
    "Fortune",
    "Trust",
    "Starting",
    "Rain",
    "Inspiration",
    "Salty",
    "What was it like being 5 years old? Where were you? What did you look like?",
    "Size",
    "Transformation",
    "Balance",
    "Threat",
    "Substitute",
    "Adapt",
    "Smile",
    "Senses",
    "House boat",
    "Dry",
    "Cold",
    "Chances",
    "Questions",
    "A speech",
    "Promise",
    "Mix",
    "What if",
    "Thrill",
    "Science",
    "Detail",
    "Speed",
    "Sky",
    "Hobbies",
    "Bubbles",
    "What was it like being 10 years old? Where were you? What did you like?",
    "Graphic",
    "Explain",
    "Borrow",
    "Transport",
    "Contrast",
    "Memory",
    "Failure",
    "Swimming",
    "Bitter",
    "Names",
    "An obituary",
    "Switch",
    "Personal",
    "Mystery",
    "Minerals",
    "Communication",
    "Bragging",
    "Horror",
    "What was it like being 12 years old? What did you like? What did you dislike?",
    "Compare",
    "Mischief",
    "Paths",
    "Create",
    "Code",
    "Scavenge",
    "Self-portrait",
    "Challenge",
    "A newsletter",
    "Canvas",
    "Hybrid",
    "Maps",
    "Abstract",
    "A snail mail letter",
    "Mode",
    "Busy",
    "Passage",
  ],
  "steno-motivations": [
    "What specific skill would you like to achieve using stenography?",
    "What would it look like/feel like if you could type using stenography?",
    "How will things be different for you when you master stenography?",
    "What would it feel like to have the skill of stenography?",
    "What would it feel like to have mastered stenography?",
    "If your goal was a t-shirt slogan, what would it say?",
    "When would you like to have your current steno goal achieved?",
    "How will you know that you have achieved your steno goal? What would the evidence of success be?",
    "What are two things you could do today to start moving towards your steno goal?",
    "What else could you do to keep momentum with steno?",
    "When could you do one thing to help you keep momentum with steno?",
    "What would an epic outcome look like for your steno journey?",
    "What is your stenographic north star?",
    "What is your current steno goal?",
    "How will you measure your steno goal success?",
    "What activities help you improve your steno speed?",
    "What activities help you improve your steno vocabulary?",
    "What activities help you improve your steno briefing and stroke efficiency?",
    "What activities help you improve your steno ergonomics?",
    "What is an achievable next milestone for you on your steno journey?",
    "How much effort are you willing to put into steno practice?",
    "How much effort have you put into steno practice?",
    "How much effort have you recently put into steno practice?",
    "What stops you doing more steno practice?",
    "What obstacles are there to your steno success?",
    "Is there a lovable project that you could do with steno to keep you motivated?",
    "What is the next part of steno you need to learn?",
    "What is your target performance level with steno?",
    "What tools and resources do you need for your stenography journey?",
    "What tools do you need to write comfortably with stenography?",
    "What will the next 20 hours of your steno practice look like?",
    "When will you next spend time concentrating on improving your steno skill?",
    "How might you fix mistakes faster?",
    "How might you spot steno mistakes quickly?",
    "When could you do a short burst of steno practice?",
    "How could you squeeze in more steno practice?",
    "Where will you be when you next practice steno?",
    "How might you get 1% better at steno today?",
    "How might you learn a little more about steno?",
    "How might you get more realistic steno practice?",
    "Have you considered an accountability buddy for your steno practice?",
    "Who could help you be successful at steno?",
    "How will you remember to do steno practice?",
    "Who has helped you with your steno practice?",
    "Who might you help with steno?",
    "What are your expectations about steno?",
    "How might you close the gap between your steno expectations and reality?",
    "What does steno success look like?",
    "What are your options for improving your steno skill?",
    "How might you spend your time, money, or energy on steno?",
    "What's the most likely way your steno journey might be disrupted?",
    "Imagine you've been wildly successful at mastering steno. What helped you get there?",
    "Suppose you've been unsuccessful at mastering steno. What stopped you getting there? How might you tackle that?",
    "What distracts you from mastering steno?",
    "How will you know what you're getting better at steno?",
    "How will you know you're getting more comfortable with steno?",
    "What makes writing with steno feel comfortable or uncomfortable?",
    "What's the slowest you could write with steno and still feel productive?",
    "What's the slowest you could write with steno and feel comfortable?",
    "What's the fastest you could write with steno with 100% accuracy?",
    "How frequently do you practice steno?",
    "How often do you revise more unusual words or steno briefs?",
    "What leads to a successful steno study session for you?",
    "What is your prediction about your steno skill one month from now?",
    "What activities will improve your steno skill? How might you test the effectiveness of those activites?",
    "What helps you remember steno briefs?",
    "What helps you concentrate?",
    "What helps you with recall?",
    "What's missing from your steno practice?",
    "What does steno mean to you?",
    "What motivates you about steno?",
    "What's an example of something that helps you practice steno?",
    "How do you prioritise steno practice?",
    "On a scale of 1 to 10, what is your current level of motivation?",
    "What is important to you about stenography?",
    "What is the next small step you can take to improve your steno skill?",
    "What is an even smaller step you could take to improve your steno skill?",
    "What is the next smallest milestone on your steno journey?",
    "How should you go about thinking about steno practice?",
    "What are the benefits of steno to you?",
    "What do you hope to achieve with steno in the next week?",
    "What do you hope to achieve with steno today?",
    "What is the purpose of steno for you?",
    "What is holding you back from steno success?",
    "What concerns do you have about steno?",
    "What have you tried so far to master steno?",
    "When do steno problems occur?",
    "What's working well for you with steno?",
    "If you could do your steno journey over again, what would you do differently?",
    "How well do you practice?",
    "What is your action plan for mastering steno?",
    "Are there advantages or disadvantages to starting your steno studies sooner or later?",
    "How many prefixes and suffixes can you write?",
    "How often do you take breaks?",
    "What's your steno posture like?",
    "How effectively do you use prefix and suffix entries?", // End of original entries
    "What specific skill would you like to achieve using stenography?",
    "What would it look like/feel like if you could type using stenography?",
    "How will things be different for you when you master stenography?",
    "What would it feel like to have the skill of stenography?",
    "What would it feel like to have mastered stenography?",
    "If your goal was a t-shirt slogan, what would it say?",
    "When would you like to have your current steno goal achieved?",
    "How will you know that you have achieved your steno goal? What would the evidence of success be?",
    "What are two things you could do today to start moving towards your steno goal?",
    "What else could you do to keep momentum with steno?",
    "When could you do one thing to help you keep momentum with steno?",
    "What would an epic outcome look like for your steno journey?",
    "What is your stenographic north star?",
    "What is your current steno goal?",
    "How will you measure your steno goal success?",
    "What activities help you improve your steno speed?",
    "What activities help you improve your steno vocabulary?",
    "What activities help you improve your steno briefing and stroke efficiency?",
    "What activities help you improve your steno ergonomics?",
    "What is an achievable next milestone for you on your steno journey?",
    "How much effort are you willing to put into steno practice?",
    "How much effort have you put into steno practice?",
    "How much effort have you recently put into steno practice?",
    "What stops you doing more steno practice?",
    "What obstacles are there to your steno success?",
    "Is there a lovable project that you could do with steno to keep you motivated?",
    "What is the next part of steno you need to learn?",
    "What is your target performance level with steno?",
    "What tools and resources do you need for your stenography journey?",
    "What tools do you need to write comfortably with stenography?",
    "What will the next 20 hours of your steno practice look like?",
    "When will you next spend time concentrating on improving your steno skill?",
    "How might you fix mistakes faster?",
    "How might you spot steno mistakes quickly?",
    "When could you do a short burst of steno practice?",
    "How could you squeeze in more steno practice?",
    "Where will you be when you next practice steno?",
    "How might you get 1% better at steno today?",
    "How might you learn a little more about steno?",
    "How might you get more realistic steno practice?",
    "Have you considered an accountability buddy for your steno practice?",
    "Who could help you be successful at steno?",
    "How will you remember to do steno practice?",
    "Who has helped you with your steno practice?",
    "Who might you help with steno?",
    "What are your expectations about steno?",
    "How might you close the gap between your steno expectations and reality?",
    "What does steno success look like?",
    "What are your options for improving your steno skill?",
    "How might you spend your time, money, or energy on steno?",
    "What's the most likely way your steno journey might be disrupted?",
    "Imagine you've been wildly successful at mastering steno. What helped you get there?",
    "Suppose you've been unsuccessful at mastering steno. What stopped you getting there? How might you tackle that?",
    "What distracts you from mastering steno?",
    "How will you know what you're getting better at steno?",
    "How will you know you're getting more comfortable with steno?",
    "What makes writing with steno feel comfortable or uncomfortable?",
    "What's the slowest you could write with steno and still feel productive?",
    "What's the slowest you could write with steno and feel comfortable?",
    "What's the fastest you could write with steno with 100% accuracy?",
    "How frequently do you practice steno?",
    "How often do you revise more unusual words or steno briefs?",
    "What leads to a successful steno study session for you?",
    "What is your prediction about your steno skill one month from now?",
    "What activities will improve your steno skill? How might you test the effectiveness of those activites?",
    "What helps you remember steno briefs?",
    "What helps you concentrate?",
    "What helps you with recall?",
    "What's missing from your steno practice?",
    "What does steno mean to you?",
    "What motivates you about steno?",
    "What's an example of something that helps you practice steno?",
    "How do you prioritise steno practice?",
    "On a scale of 1 to 10, what is your current level of motivation?",
    "What is important to you about stenography?",
    "What is the next small step you can take to improve your steno skill?",
    "What is an even smaller step you could take to improve your steno skill?",
    "What is the next smallest milestone on your steno journey?",
    "How should you go about thinking about steno practice?",
    "What are the benefits of steno to you?",
    "What do you hope to achieve with steno in the next week?",
    "What do you hope to achieve with steno today?",
    "What is the purpose of steno for you?",
    "What is holding you back from steno success?",
    "What concerns do you have about steno?",
    "What have you tried so far to master steno?",
    "When do steno problems occur?",
    "What's working well for you with steno?",
    "If you could do your steno journey over again, what would you do differently?",
    "How well do you practice?",
    "What is your action plan for mastering steno?",
    "Are there advantages or disadvantages to starting your steno studies sooner or later?",
    "How many prefixes and suffixes can you write?",
    "How often do you take breaks?",
    "What's your steno posture like?",
    "How effectively do you use prefix and suffix entries?",
    "What specific skill would you like to achieve using stenography?",
    "What would it look like/feel like if you could type using stenography?",
    "How will things be different for you when you master stenography?",
    "What would it feel like to have the skill of stenography?",
    "What would it feel like to have mastered stenography?",
    "If your goal was a t-shirt slogan, what would it say?",
    "When would you like to have your current steno goal achieved?",
    "How will you know that you have achieved your steno goal? What would the evidence of success be?",
    "What are two things you could do today to start moving towards your steno goal?",
    "What else could you do to keep momentum with steno?",
    "When could you do one thing to help you keep momentum with steno?",
    "What would an epic outcome look like for your steno journey?",
    "What is your stenographic north star?",
    "What is your current steno goal?",
    "How will you measure your steno goal success?",
    "What activities help you improve your steno speed?",
    "What activities help you improve your steno vocabulary?",
    "What activities help you improve your steno briefing and stroke efficiency?",
    "What activities help you improve your steno ergonomics?",
    "What is an achievable next milestone for you on your steno journey?",
    "How much effort are you willing to put into steno practice?",
    "How much effort have you put into steno practice?",
    "How much effort have you recently put into steno practice?",
    "What stops you doing more steno practice?",
    "What obstacles are there to your steno success?",
    "Is there a lovable project that you could do with steno to keep you motivated?",
    "What is the next part of steno you need to learn?",
    "What is your target performance level with steno?",
    "What tools and resources do you need for your stenography journey?",
    "What tools do you need to write comfortably with stenography?",
    "What will the next 20 hours of your steno practice look like?",
    "When will you next spend time concentrating on improving your steno skill?",
    "How might you fix mistakes faster?",
    "How might you spot steno mistakes quickly?",
    "When could you do a short burst of steno practice?",
    "How could you squeeze in more steno practice?",
    "Where will you be when you next practice steno?",
    "How might you get 1% better at steno today?",
    "How might you learn a little more about steno?",
    "How might you get more realistic steno practice?",
    "Have you considered an accountability buddy for your steno practice?",
    "Who could help you be successful at steno?",
    "How will you remember to do steno practice?",
    "Who has helped you with your steno practice?",
    "Who might you help with steno?",
    "What are your expectations about steno?",
    "How might you close the gap between your steno expectations and reality?",
    "What does steno success look like?",
    "What are your options for improving your steno skill?",
    "How might you spend your time, money, or energy on steno?",
    "What's the most likely way your steno journey might be disrupted?",
    "Imagine you've been wildly successful at mastering steno. What helped you get there?",
    "Suppose you've been unsuccessful at mastering steno. What stopped you getting there? How might you tackle that?",
    "What distracts you from mastering steno?",
    "How will you know what you're getting better at steno?",
    "How will you know you're getting more comfortable with steno?",
    "What makes writing with steno feel comfortable or uncomfortable?",
    "What's the slowest you could write with steno and still feel productive?",
    "What's the slowest you could write with steno and feel comfortable?",
    "What's the fastest you could write with steno with 100% accuracy?",
    "How frequently do you practice steno?",
    "How often do you revise more unusual words or steno briefs?",
    "What leads to a successful steno study session for you?",
    "What is your prediction about your steno skill one month from now?",
    "What activities will improve your steno skill? How might you test the effectiveness of those activites?",
    "What helps you remember steno briefs?",
    "What helps you concentrate?",
    "What helps you with recall?",
    "What's missing from your steno practice?",
    "What does steno mean to you?",
    "What motivates you about steno?",
    "What's an example of something that helps you practice steno?",
    "How do you prioritise steno practice?",
    "On a scale of 1 to 10, what is your current level of motivation?",
    "What is important to you about stenography?",
    "What is the next small step you can take to improve your steno skill?",
    "What is an even smaller step you could take to improve your steno skill?",
    "What is the next smallest milestone on your steno journey?",
    "How should you go about thinking about steno practice?",
    "What are the benefits of steno to you?",
    "What do you hope to achieve with steno in the next week?",
    "What do you hope to achieve with steno today?",
    "What is the purpose of steno for you?",
    "What is holding you back from steno success?",
    "What concerns do you have about steno?",
    "What have you tried so far to master steno?",
    "When do steno problems occur?",
    "What's working well for you with steno?",
    "If you could do your steno journey over again, what would you do differently?",
    "How well do you practice?",
    "What is your action plan for mastering steno?",
    "Are there advantages or disadvantages to starting your steno studies sooner or later?",
    "How many prefixes and suffixes can you write?",
    "How often do you take breaks?",
    "What's your steno posture like?",
    "How effectively do you use prefix and suffix entries?",
    "What specific skill would you like to achieve using stenography?",
    "What would it look like/feel like if you could type using stenography?",
    "How will things be different for you when you master stenography?",
    "What would it feel like to have the skill of stenography?",
    "What would it feel like to have mastered stenography?",
    "If your goal was a t-shirt slogan, what would it say?",
    "When would you like to have your current steno goal achieved?",
    "How will you know that you have achieved your steno goal? What would the evidence of success be?",
    "What are two things you could do today to start moving towards your steno goal?",
    "What else could you do to keep momentum with steno?",
    "When could you do one thing to help you keep momentum with steno?",
    "What would an epic outcome look like for your steno journey?",
    "What is your stenographic north star?",
    "What is your current steno goal?",
    "How will you measure your steno goal success?",
    "What activities help you improve your steno speed?",
    "What activities help you improve your steno vocabulary?",
    "What activities help you improve your steno briefing and stroke efficiency?",
    "What activities help you improve your steno ergonomics?",
    "What is an achievable next milestone for you on your steno journey?",
    "How much effort are you willing to put into steno practice?",
    "How much effort have you put into steno practice?",
    "How much effort have you recently put into steno practice?",
    "What stops you doing more steno practice?",
    "What obstacles are there to your steno success?",
    "Is there a lovable project that you could do with steno to keep you motivated?",
    "What is the next part of steno you need to learn?",
    "What is your target performance level with steno?",
    "What tools and resources do you need for your stenography journey?",
    "What tools do you need to write comfortably with stenography?",
    "What will the next 20 hours of your steno practice look like?",
    "When will you next spend time concentrating on improving your steno skill?",
    "How might you fix mistakes faster?",
    "How might you spot steno mistakes quickly?",
    "When could you do a short burst of steno practice?",
    "How could you squeeze in more steno practice?",
    "Where will you be when you next practice steno?",
    "How might you get 1% better at steno today?",
    "How might you learn a little more about steno?",
    "How might you get more realistic steno practice?",
    "Have you considered an accountability buddy for your steno practice?",
    "Who could help you be successful at steno?",
    "How will you remember to do steno practice?",
    "Who has helped you with your steno practice?",
    "Who might you help with steno?",
    "What are your expectations about steno?",
    "How might you close the gap between your steno expectations and reality?",
    "What does steno success look like?",
    "What are your options for improving your steno skill?",
    "How might you spend your time, money, or energy on steno?",
    "What's the most likely way your steno journey might be disrupted?",
    "Imagine you've been wildly successful at mastering steno. What helped you get there?",
    "Suppose you've been unsuccessful at mastering steno. What stopped you getting there? How might you tackle that?",
    "What distracts you from mastering steno?",
    "How will you know what you're getting better at steno?",
    "How will you know you're getting more comfortable with steno?",
    "What makes writing with steno feel comfortable or uncomfortable?",
    "What's the slowest you could write with steno and still feel productive?",
    "What's the slowest you could write with steno and feel comfortable?",
    "What's the fastest you could write with steno with 100% accuracy?",
    "How frequently do you practice steno?",
    "How often do you revise more unusual words or steno briefs?",
    "What leads to a successful steno study session for you?",
    "What is your prediction about your steno skill one month from now?",
    "What activities will improve your steno skill? How might you test the effectiveness of those activites?",
    "What helps you remember steno briefs?",
    "What helps you concentrate?",
    "What helps you with recall?",
    "What's missing from your steno practice?",
    "What does steno mean to you?",
    "What motivates you about steno?",
    "What's an example of something that helps you practice steno?",
    "How do you prioritise steno practice?",
    "On a scale of 1 to 10, what is your current level of motivation?",
    "What is important to you about stenography?",
    "What is the next small step you can take to improve your steno skill?",
    "What is an even smaller step you could take to improve your steno skill?",
    "What is the next smallest milestone on your steno journey?",
  ],
  "journalling": [
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Life story",
    "Change",
    "Reflection",
    "Lessons",
    "Wishes", // End of original entries
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
    "What have you achieved?",
    "Thoughts",
    "Ideas",
    "Options",
    "Approaches",
    "Action",
    "Feelings",
    "Gratitude",
    "Accomplishments",
    "What have you learned this week?",
    "What's on your mind?",
    "What happened yesterday?",
    "What happened today?",
    "What will do you today?",
    "What will do you this week?",
    "What have you learned?",
  ],
  "open-ended": [],
};

export default prompts;
