const punctuationDescriptions: { [punctuationSymbol: string]: string } = {
  "`": "grave",
  "“": "left double quotation mark",
  "”": "right double quotation mark",
  "‘": "left single quotation mark",
  "’": "right single quotation mark",
  "–": "en dash",
  "—": "em dash",
  "≈": "almost equal to",
  "&": "ampersand",
  "⟨": "mathematical left angle bracket",
  "⟩": "mathematical right angle bracket",
  "*": "asterisk",
  "⁂": "asterism",
  "@": "at sign",
  "\\": "backslash",
  "‱": "per ten thousand sign",
  "∵": "because sign",
  "[": "left square bracket",
  "]": "right square bracket",
  "{": "left curly bracket",
  "}": "right curly bracket",
  "•": "bullet",
  "⁁": "caret insertion point",
  "⎀": "insertion symbol",
  "‸": "caret (proofreading)",
  "^": "circumflex",
  ":": "colon",
  ",": "comma",
  "⁒": "commercial minus sign",
  "🄯": "copyleft sign",
  "©": "copyright sign",
  "¤": "currency sign",
  "‡": "double dagger",
  "†": "dagger",
  "°": "degree sign",
  "⌀": "diameter",
  "÷": "division sign",
  "◌": "dotted circle",
  "⸗": "double oblique hyphen",
  "⹀": "double hyphen",
  "…": "ellipsis",
  "=": "equals sign",
  "℮": "estimated sign",
  "!": "exclamation mark",
  "ª": "feminine ordinal indicator",
  "❧": "rotated floral heart",
  "❦": "floral heart",
  ".": "full stop",
  "♀": "female sign",
  "♂": "male sign",
  "⚥": "male and female sign",
  ">": "greater-than sign",
  "»": "right-pointing double angle quotation mark",
  "«": "left-pointing double angle quotation mark",
  "‐": "hyphen",
  "-": "hyphen-minus",
  "·": "interpunct",
  "‽": "interrobang",
  "¡": "inverted exclamation mark",
  "¿": "inverted question mark",
  "<": "less-than sign",
  "◊": "lozenge",
  "☞": "manicule",
  "º": "masculine ordinal indicator",
  "−": "minus sign",
  "×": "multiplication sign",
  "#": "number sign",
  "№": "numero sign",
  ")": "right parenthesis",
  "(": "left parenthesis",
  "%": "percent sign",
  "‰": "per mille",
  "¶": "pilcrow",
  "+": "plus sign",
  "±": "plus–minus sign",
  "″": "double prime",
  "‴": "triple prime",
  "′": "prime",
  "?": "question mark",
  '"': "quotation mark",
  "'": "apostrophe",
  "®": "registered trademark symbol",
  "§": "section sign",
  ";": "semicolon",
  "℠": "service mark symbol",
  "/": "slash",
  "℗": "sound recording copyright symbol",
  "⌑": "square lozenge",
  "∴": "therefore sign",
  "⁀": "tie",
  "~": "tilde",
  "™": "trademark symbol",
  "_": "underscore",
  "|": "vertical bar",
};

const describePunctuation = (currentPhrase: string): string => {
  return punctuationDescriptions[currentPhrase] ?? ""; // Nullish coalescing operator
};

export default describePunctuation;
