import rankAffixes from "./rankAffixes";

import type {
  StenoDictionary,
  StrokeAndDictionaryAndNamespace,
} from "../types";

const affixMisstrokes: StenoDictionary = {
  "#-D": "{^ed}",
  "*EB": "{^en}",
  "*PBS": "{^iness}",
  "*S": "{^s}",
  "-DZ": "{^ed}",
  "-GS": "{^s}",
  "-SZ": "{^s}",
  "12ER7B/SKWRO": "{sterno^}",
  "340*EU7B": "{amino^}",
  "340EU67": "{amino^}",
  "A*ES": "{^'s}",
  "A*EUPBT": "{anti-^}",
  "A*UT": "{auto^}",
  "A/340*EU7B": "{amino^}",
  "AER/SKWRO": "{aero^}",
  "AEUR/TEU": "{^arity}",
  "AL/TEU": "{^ality}",
  "AO*EPB": "{^ean}",
  "AO*UT": "{out^}",
  "AOPB": "{on^}",
  "AOT": "{out^}",
  "AOUFR": "{over^}",
  "APB/TAOEU": "{anti^}",
  "APB/TEU": "{anti^}",
  "AUB": "{sub^}",
  "EBG/HREU": "{^ically}",
  "EFLT": "{^est}",
  "EUL/TEU": "{^ility}",
  "H/HREU": "{^ly}",
  "HREUPBS": "{^liness}",
  "HRO*": "{^ol}",
  "HRO*EUFPL/SKWRO": "{lympho^}",
  "KAO*ERP": "{^keeper}",
  "KAUB": "{sub^}",
  "KOBG/SKWRUS": "{^coccus}",
  "KOURPBT": "{counter^}",
  "KPWHROS/SO": "{glosso^}",
  "KR*GS": '{^"}',
  "KR-GS": '{^"}',
  "KRO": "{co-^}",
  "KW-GS": '{"^}',
  "KWEU": "{^y}",
  "KWRA*U": "{^ier}",
  "KWROEFR": "{over^}",
  "KWROUFR": "{over^}",
  "KWROUT": "{out^}",
  "KWRUP": "{up^}",
  "KWRUPB": "{un^}",
  "KWRUPBD": "{under^}",
  "KWRUS": "{^us}",
  "O*/PHAOET/*ER": "{^-o-meter}",
  "O*/SREUGS": "{^-o-vision}",
  "O*EF": "{^over}",
  "O*US": "{^us}",
  "OPL/TER": "{^ometer}",
  "PH*EUD": "{mid-^}",
  "PHA*EUBG/-G": "{^making}",
  "PHAO*EUFG": "{^imizing}",
  "PHAO*EUR": "{^meier}",
  "PHAUPB": "{non-^}",
  "PHO*PBG/*ER": "{^monger}",
  "PHRO*EUPB": "{immuno^}",
  "PRE": "{pre-^}",
  "R-D": "{^red}",
  "SAO*EUD/A*L": "{^cidal}",
  "SAOUD/A*L": "{^cidal}",
  "SAOUPS": "{super^}",
  "SAUP": "{sub^}",
  "SHUS": "{^tious}",
  "SKPWREPB/EUS/TEU": "{^genicity}",
  "SKWR*US": "{^us}",
  "SKWRAOED": "{^ed}",
  "SKWROEFR": "{^Over}",
  "SKWRUS": "{^us}",
  "SPR": "{super^}",
  "SPWR": "{inter^}",
  "T*EU": "{^ity}",
  "TAO*EUT": "{^tight}",
  "TEUFT": "{^ticity}",
  "TKEUZ": "{dis^}",
  "TKOERBS": "{^adocious}",
  "TPA*EUBGS": "{^ification}",
  "TPA*EUGS": "{^ification}",
  "TPHAER": "{^ary}",
  "TPHALT": "{^ality}",
  "TPHAUPB": "{non-^}",
  "UB": "{un^}",
  "UFPB": "{un^}",
  "UPBDZ": "{under^}",
  "WUS": "{^uous}",
};

describe("rankAffixes", () => {
  it("prefers O*EUT to A*UT for 'auto'", () => {
    const outlinesAndSourceDicts: StrokeAndDictionaryAndNamespace[] = [
      ["A*UT/SKWRO", "personal.json", "user"],
      ["O*EUT", "personal.json", "user"],
      ["A*UT", "personal.json", "user"],
    ];
    const result = rankAffixes(
      outlinesAndSourceDicts,
      affixMisstrokes,
      "{auto^}"
    );
    expect(result).toEqual([
      ["O*EUT", "personal.json", "user"],
      ["A*UT/SKWRO", "personal.json", "user"], // because this is not marked as a misstroke
      ["A*UT", "personal.json", "user"], // because this is a misstroke
    ]);
  });
});
