import mapBriefToNoNumberBarOuterThumbNumbersStenoKeys from "./mapBriefToNoNumberBarOuterThumbNumbersStenoKeys";

describe("map stroke to keys", () => {
  it("show no keys for empty brief", () => {
    let brief = "";
    expect(mapBriefToNoNumberBarOuterThumbNumbersStenoKeys(brief)).toEqual({
      leftNumberBarKey: false,
      rightNumberBarKey: false,
      leftSUpperKey: false,
      leftSLowerKey: false,
      leftTKey: false,
      leftKKey: false,
      leftPKey: false,
      leftWKey: false,
      leftHKey: false,
      leftRKey: false,
      leftAKey: false,
      leftOKey: false,
      leftStarUpperKey: false,
      leftStarLowerKey: false,
      rightStarUpperKey: false,
      rightStarLowerKey: false,
      dashKey: false,
      rightEKey: false,
      rightUKey: false,
      rightFKey: false,
      rightRKey: false,
      rightPKey: false,
      rightBKey: false,
      rightLKey: false,
      rightGKey: false,
      rightTKey: false,
      rightSKey: false,
      rightDKey: false,
      rightZKey: false,
    });
  });

  it('shows left-hand T for "it"', () => {
    let brief = "T";
    expect(mapBriefToNoNumberBarOuterThumbNumbersStenoKeys(brief)).toEqual({
      leftNumberBarKey: false,
      rightNumberBarKey: false,
      leftSUpperKey: false,
      leftSLowerKey: false,
      leftTKey: true,
      leftKKey: false,
      leftPKey: false,
      leftWKey: false,
      leftHKey: false,
      leftRKey: false,
      leftAKey: false,
      leftOKey: false,
      leftStarUpperKey: false,
      leftStarLowerKey: false,
      rightStarUpperKey: false,
      rightStarLowerKey: false,
      dashKey: false,
      rightEKey: false,
      rightUKey: false,
      rightFKey: false,
      rightRKey: false,
      rightPKey: false,
      rightBKey: false,
      rightLKey: false,
      rightGKey: false,
      rightTKey: false,
      rightSKey: false,
      rightDKey: false,
      rightZKey: false,
    });
  });

  it('shows right-hand -T for "the"', () => {
    let brief = "-T";
    expect(mapBriefToNoNumberBarOuterThumbNumbersStenoKeys(brief)).toEqual({
      leftNumberBarKey: false,
      rightNumberBarKey: false,
      leftSUpperKey: false,
      leftSLowerKey: false,
      leftTKey: false,
      leftKKey: false,
      leftPKey: false,
      leftWKey: false,
      leftHKey: false,
      leftRKey: false,
      leftAKey: false,
      leftOKey: false,
      leftStarUpperKey: false,
      leftStarLowerKey: false,
      rightStarUpperKey: false,
      rightStarLowerKey: false,
      dashKey: false,
      rightEKey: false,
      rightUKey: false,
      rightFKey: false,
      rightRKey: false,
      rightPKey: false,
      rightBKey: false,
      rightLKey: false,
      rightGKey: false,
      rightTKey: true,
      rightSKey: false,
      rightDKey: false,
      rightZKey: false,
    });
  });

  it('shows both S keys for "is"', () => {
    let brief = "S";
    expect(mapBriefToNoNumberBarOuterThumbNumbersStenoKeys(brief)).toEqual({
      leftNumberBarKey: true,
      rightNumberBarKey: true,
      leftSUpperKey: false,
      leftSLowerKey: false,
      leftTKey: false,
      leftKKey: false,
      leftPKey: false,
      leftWKey: false,
      leftHKey: false,
      leftRKey: false,
      leftAKey: false,
      leftOKey: false,
      leftStarUpperKey: false,
      leftStarLowerKey: false,
      rightStarUpperKey: false,
      rightStarLowerKey: false,
      dashKey: false,
      rightEKey: false,
      rightUKey: false,
      rightFKey: false,
      rightRKey: false,
      rightPKey: false,
      rightBKey: false,
      rightLKey: false,
      rightGKey: false,
      rightTKey: true,
      rightSKey: false,
      rightDKey: false,
      rightZKey: false,
    });
  });

  it("shows both number keys for numbers like 3", () => {
    let brief = "3";
    expect(mapBriefToNoNumberBarOuterThumbNumbersStenoKeys(brief)).toEqual({
      leftNumberBarKey: true,
      rightNumberBarKey: true,
      leftSUpperKey: false,
      leftSLowerKey: false,
      leftTKey: false,
      leftKKey: false,
      leftPKey: true,
      leftWKey: false,
      leftHKey: false,
      leftRKey: false,
      leftAKey: false,
      leftOKey: false,
      leftStarUpperKey: false,
      leftStarLowerKey: false,
      rightStarUpperKey: false,
      rightStarLowerKey: false,
      dashKey: false,
      rightEKey: false,
      rightUKey: false,
      rightFKey: false,
      rightRKey: false,
      rightPKey: false,
      rightBKey: false,
      rightLKey: false,
      rightGKey: false,
      rightTKey: false,
      rightSKey: false,
      rightDKey: false,
      rightZKey: false,
    });
  });

  it("show all star keys for starred brief", () => {
    let brief = "AO*EUS";
    expect(mapBriefToNoNumberBarOuterThumbNumbersStenoKeys(brief)).toEqual({
      leftNumberBarKey: false,
      rightNumberBarKey: false,
      leftSUpperKey: false,
      leftSLowerKey: false,
      leftTKey: false,
      leftKKey: false,
      leftPKey: false,
      leftWKey: false,
      leftHKey: false,
      leftRKey: false,
      leftAKey: true,
      leftOKey: true,
      leftStarUpperKey: true,
      leftStarLowerKey: true,
      rightStarUpperKey: true,
      rightStarLowerKey: true,
      dashKey: false,
      rightEKey: true,
      rightUKey: true,
      rightFKey: false,
      rightRKey: false,
      rightPKey: false,
      rightBKey: false,
      rightLKey: false,
      rightGKey: false,
      rightTKey: false,
      rightSKey: false,
      rightDKey: false,
      rightZKey: false,
    });
  });

  it('show keys for dash-only brief "welcome"', () => {
    let brief = "HR-BG";
    expect(mapBriefToNoNumberBarOuterThumbNumbersStenoKeys(brief)).toEqual({
      leftNumberBarKey: false,
      rightNumberBarKey: false,
      leftSUpperKey: false,
      leftSLowerKey: false,
      leftTKey: false,
      leftKKey: false,
      leftPKey: false,
      leftWKey: false,
      leftHKey: true,
      leftRKey: true,
      leftAKey: false,
      leftOKey: false,
      leftStarUpperKey: false,
      leftStarLowerKey: false,
      rightStarUpperKey: false,
      rightStarLowerKey: false,
      dashKey: true,
      rightEKey: false,
      rightUKey: false,
      rightFKey: false,
      rightRKey: false,
      rightPKey: false,
      rightBKey: true,
      rightLKey: false,
      rightGKey: true,
      rightTKey: false,
      rightSKey: false,
      rightDKey: false,
      rightZKey: false,
    });
  });

  it("show nothing when given non-steno letters", () => {
    let brief = "⌘";
    expect(mapBriefToNoNumberBarOuterThumbNumbersStenoKeys(brief)).toEqual({
      leftNumberBarKey: false,
      rightNumberBarKey: false,
      leftSUpperKey: false,
      leftSLowerKey: false,
      leftTKey: false,
      leftKKey: false,
      leftPKey: false,
      leftWKey: false,
      leftHKey: false,
      leftRKey: false,
      leftAKey: false,
      leftOKey: false,
      leftStarUpperKey: false,
      leftStarLowerKey: false,
      rightStarUpperKey: false,
      rightStarLowerKey: false,
      dashKey: false,
      rightEKey: false,
      rightUKey: false,
      rightFKey: false,
      rightRKey: false,
      rightPKey: false,
      rightBKey: false,
      rightLKey: false,
      rightGKey: false,
      rightTKey: false,
      rightSKey: false,
      rightDKey: false,
      rightZKey: false,
    });
  });
});

