import mapBriefToKoreanModernCStenoKeys from "utils/stenoLayouts/mapBriefToKoreanModernCStenoKeys";

describe("map stroke to keys", () => {
  it("show no keys for empty brief", () => {
    let brief = "";
    expect(mapBriefToKoreanModernCStenoKeys(brief)).toEqual({
      the1Key: false,
      the2Key: false,
      the3Key: false,
      the4Key: false,
      the5Key: false,
      theLeftㅎKey: false,
      theLeftㅁKey: false,
      theLeftㄱKey: false,
      theLeftㅈKey: false,
      theLeftㄴKey: false,
      theLeftㄷKey: false,
      theLeftㅇKey: false,
      theLeftㅅKey: false,
      theLeftㅂKey: false,
      theLeftㄹKey: false,
      theㅗKey: false,
      theㅏKey: false,
      theㅜKey: false,
      theStarKey: false,
      theㅓKey: false,
      theㅣKey: false,
      the6Key: false,
      the7Key: false,
      the8Key: false,
      the9Key: false,
      the0Key: false,
      theRightㅎKey: false,
      theRightㅇKey: false,
      theRightㄹKey: false,
      theRightㄱKey: false,
      theRightㄷKey: false,
      theRightㅂKey: false,
      theRightㄴKey: false,
      theRightㅅKey: false,
      theRightㅈKey: false,
      theRightㅁKey: false,
    });
  });

  it('shows left-hand ㄱ', () => {
    let brief = "ㄱ";
    expect(mapBriefToKoreanModernCStenoKeys(brief)).toEqual({
      the1Key: false,
      the2Key: false,
      the3Key: false,
      the4Key: false,
      the5Key: false,
      theLeftㅎKey: false,
      theLeftㅁKey: false,
      theLeftㄱKey: true,
      theLeftㅈKey: false,
      theLeftㄴKey: false,
      theLeftㄷKey: false,
      theLeftㅇKey: false,
      theLeftㅅKey: false,
      theLeftㅂKey: false,
      theLeftㄹKey: false,
      theㅗKey: false,
      theㅏKey: false,
      theㅜKey: false,
      theStarKey: false,
      theㅓKey: false,
      theㅣKey: false,
      the6Key: false,
      the7Key: false,
      the8Key: false,
      the9Key: false,
      the0Key: false,
      theRightㅎKey: false,
      theRightㅇKey: false,
      theRightㄹKey: false,
      theRightㄱKey: false,
      theRightㄷKey: false,
      theRightㅂKey: false,
      theRightㄴKey: false,
      theRightㅅKey: false,
      theRightㅈKey: false,
      theRightㅁKey: false,
    });
  });

  it('show keys for 없습니까?', () => {
    let brief = "ㅇㅂ-ㅂㄴㅅ"; // 없습니까?
    expect(mapBriefToKoreanModernCStenoKeys(brief)).toEqual({
      the1Key: false,
      the2Key: false,
      the3Key: false,
      the4Key: false,
      the5Key: false,
      theLeftㅎKey: false,
      theLeftㅁKey: false,
      theLeftㄱKey: false,
      theLeftㅈKey: false,
      theLeftㄴKey: false,
      theLeftㄷKey: false,
      theLeftㅇKey: true,
      theLeftㅅKey: false,
      theLeftㅂKey: true,
      theLeftㄹKey: false,
      theㅗKey: false,
      theㅏKey: false,
      theㅜKey: false,
      theStarKey: false,
      theㅓKey: false,
      theㅣKey: false,
      the6Key: false,
      the7Key: false,
      the8Key: false,
      the9Key: false,
      the0Key: false,
      theRightㅎKey: false,
      theRightㅇKey: false,
      theRightㄹKey: false,
      theRightㄱKey: false,
      theRightㄷKey: false,
      theRightㅂKey: true,
      theRightㄴKey: true,
      theRightㅅKey: true,
      theRightㅈKey: false,
      theRightㅁKey: false,
    });
  });

  it("show nothing when given non-steno letters", () => {
    let brief = "⌘";
    expect(mapBriefToKoreanModernCStenoKeys(brief)).toEqual({
      the1Key: false,
      the2Key: false,
      the3Key: false,
      the4Key: false,
      the5Key: false,
      theLeftㅎKey: false,
      theLeftㅁKey: false,
      theLeftㄱKey: false,
      theLeftㅈKey: false,
      theLeftㄴKey: false,
      theLeftㄷKey: false,
      theLeftㅇKey: false,
      theLeftㅅKey: false,
      theLeftㅂKey: false,
      theLeftㄹKey: false,
      theㅗKey: false,
      theㅏKey: false,
      theㅜKey: false,
      theStarKey: false,
      theㅓKey: false,
      theㅣKey: false,
      the6Key: false,
      the7Key: false,
      the8Key: false,
      the9Key: false,
      the0Key: false,
      theRightㅎKey: false,
      theRightㅇKey: false,
      theRightㄹKey: false,
      theRightㄱKey: false,
      theRightㄷKey: false,
      theRightㅂKey: false,
      theRightㄴKey: false,
      theRightㅅKey: false,
      theRightㅈKey: false,
      theRightㅁKey: false,
    });
  });
});
