name: CI
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      # https://github.com/actions/checkout
      - name: 🏗️ Check out repository code
        uses: actions/checkout@v5
        with:
          submodules: true

      # https://github.com/actions/setup-node
      - name: 🏗️ Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24.14.1"
          cache: "yarn"

      - name: 🏗️ Install dependencies
        run: yarn install --immutable

      - name: ☑️ Check TypeScript compiles
        run: yarn run types

      - name: ☑️ Run tests
        run: yarn run test:ci

      - name: ☑️ Lint
        run: yarn run lint:ci

      - name: ☑️ Run a production-like staging build but without a Sentry release
        run: yarn run build:staging

      - name: ☑️ Build Storybook
        run: yarn run build-storybook
