name: CI
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      # https://github.com/actions/checkout
      - name: 🏗️ Check out repository code
        uses: actions/checkout@v6
        with:
          submodules: true

      # https://github.com/pnpm/action-setup
      - name: 🏗️ Install pnpm package manager
        uses: pnpm/action-setup@v6
        with:
          version: "10.33.0"

      # https://github.com/actions/setup-node
      - name: 🏗️ Install Node.js and cache packages
        uses: actions/setup-node@v6
        with:
          node-version: "24.14.1"
          # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
          cache: "pnpm"

      - name: 🏗️ Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ☑️ Check TypeScript compiles
        run: pnpm run types

      - name: ☑️ Run tests
        run: pnpm run test:ci

      - name: ☑️ Lint
        run: pnpm run lint:ci

      - name: ☑️ Run a production-like staging build but without a Sentry release
        run: pnpm run build:staging

      - name: ☑️ Build Storybook
        run: pnpm run build-storybook
