name: Visual Regression Testing
on:
  # pull_request:
  #   types: [opened, reopened, ready_for_review, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      # https://github.com/actions/checkout
      - name: 🏗️ Check out repository code
        uses: actions/checkout@v5
        with:
          submodules: true
          fetch-depth: 0

      # https://github.com/actions/setup-node
      - name: 🏗️ Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24.14.1"
          cache: "yarn"

      - name: 🏗️ Install dependencies
        run: yarn install --immutable

      # https://github.com/chromaui/action
      # https://github.com/chromaui/chromatic-cli
      - name: ☑️ Build Chromatic
        uses: chromaui/action@v16.2.0
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: ${{ github.ref == 'refs/heads/master' && true || false }}
          skip: "dependabot/**"
          # dryRun: true
